require("jmonteiro.plugins-setup")
require("jmonteiro.core.options")
require("jmonteiro.core.keymaps")
require("jmonteiro.core.colorscheme")
require("jmonteiro.plugins.comment")
require("jmonteiro.plugins.lualine")
require("jmonteiro.plugins.treesitter")
-- require("jmonteiro.plugins.lsp.lspconfig")
-- require("jmonteiro.plugins.lsp.lspsaga")
require("jmonteiro.plugins.telescope")
require("jmonteiro.plugins.endwise")
require("jmonteiro.plugins.nvim-cmp")
require("jmonteiro.plugins.mason")

